package de.agdb.backend.entities.schedule_wrapper_objects;

import javax.persistence.*;

@Entity
@Table(name = "categorysetup")
public class CategoriesWrapper {


    // An autogenerated id (unique for each schedule in the db)
    @Id
    @Column(name = "CATEGORYSETUP_ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    int numberParticipants;
    String category;

    public CategoriesWrapper() {
    }

    public CategoriesWrapper(int numberParticipants, String category) {
        this.numberParticipants = numberParticipants;
        this.category = category;
    }

    public int getNumberParticipants() {
        return numberParticipants;
    }
    public void setNumberParticipants(int numberParticipants) {
        this.numberParticipants = numberParticipants;
    }

    public String getCategory() {
        return category;
    }
    public void setCategory(String category) {
        this.category = category;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

}
