package de.agdb.backend.entities.schedule_wrapper_objects;

import de.agdb.backend.entities.Contact;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "categorysetup")
public class CategoriesWrapper {


    // An autogenerated id (unique for each schedule in the db)
    @Id
    @Column(name = "CATEGORYSETUP_ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private int numberParticipants;
    private String categoryTitle;
    private long categoryId;



    public List<AssignedContact> getAssignedContacts() {
        return this.assignedContacts;
    }


    public void addAssignedContact(AssignedContact ac) {
        this.assignedContacts.add(ac);
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = AssignedContact.class)
    @JoinTable(name = "CATEGORYSETUP_ASSIGNEDCONTACT", joinColumns = { @JoinColumn(name = "CATEGORYSETUP_ID") }, inverseJoinColumns = { @JoinColumn(name = "ASSIGNEDCONTACT_ID") })
    @Fetch(value = FetchMode.SUBSELECT)
    private List<AssignedContact> assignedContacts;

    public CategoriesWrapper() {
    }



    public void removeAssignedContact(Long contactId) {
        for (int i=0;i<assignedContacts.size();i++) {
            if (contactId.equals(assignedContacts.get(i).getContact().getId())) {
                assignedContacts.remove(i);
                break;
            }
        }
    }



    public CategoriesWrapper(int numberParticipants, String categoryTitle, long categoryId) {
        this.numberParticipants = numberParticipants;
        this.categoryTitle = categoryTitle;
        this.categoryId = categoryId;
    }

    public int getNumberParticipants() {
        return numberParticipants;
    }
    public void setNumberParticipants(int numberParticipants) {
        this.numberParticipants = numberParticipants;
    }

    public String getCategoryTitle() {
        return this.categoryTitle;
    }
    public void setCategoryTitle(String categoryTitle) {
        this.categoryTitle = categoryTitle;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }

}
