package de.agdb.backend.entities.schedule_wrapper_objects;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "timelocation")
public class TimeLocationWrapper {


    // An autogenerated id (unique for each schedule in the db)
    @Id
    @Column(name = "TIMELOCATION_ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    int startHour;
    int startMin;
    int endHour;
    int endMin;
    String location;
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = CategoriesWrapper.class)
    @JoinTable(name = "TIMELOCATION_CATEGORYSETUP", joinColumns = { @JoinColumn(name = "TIMELOCATION_ID") }, inverseJoinColumns = { @JoinColumn(name = "CATEGORYSETUP_ID") })
    List<CategoriesWrapper> categoriesList;


    public TimeLocationWrapper() {

    }

    public TimeLocationWrapper(int startHour, int startMin, int endHour, int endMin, String location) {
        this.startHour = startHour;
        this.startMin = startMin;
        this.endHour = endHour;
        this.endMin = endMin;
        this.location = location;
        this.categoriesList = new ArrayList<>();

    }

    public void addCategory(CategoriesWrapper e) {
        categoriesList.add(e);
    }

    public void removeCategory(CategoriesWrapper e) {
        categoriesList.remove(e);

    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }



    public List<CategoriesWrapper> getCategoriesList() {
        return this.categoriesList;
    }

    public void setCategoriesList(List<CategoriesWrapper> categoriesList) {
        this.categoriesList = categoriesList;
    }

    public long getId() { return id; }

    public void setId(long id) { this.id = id; }

    public int getStartHour() {
        return startHour;
    }

    public void setStartHour(int startHour) {
        this.startHour = startHour;
    }

    public int getStartMin() {
        return startMin;
    }

    public void setStartMin(int startMin) {
        this.startMin = startMin;
    }

    public int getEndHour() {
        return endHour;
    }

    public void setEndHour(int endHour) {
        this.endHour = endHour;
    }

    public int getEndMin() {
        return endMin;
    }

    public void setEndMin(int endMin) {
        this.endMin = endMin;
    }

}
