package de.agdb.backend.data_model.schedule_wrapper_objects;

import de.agdb.backend.data_model.Contact;

import javax.persistence.*;

@Entity
@Table(name = "assignedcontact")
public class AssignedContact {

    public AssignedContact() {

    }

    public AssignedContact(Contact contact) {
        this.contact = contact;
    }

    public boolean isParticipating() {
        return isParticipating;
    }

    public void setParticipating(boolean participating) {
        isParticipating = participating;
    }

    public Contact getContact() {
        return contact;
    }

    public void setContact(Contact contact) {
        this.contact = contact;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    private boolean isParticipating = false;
    private Contact contact;



    // An autogenerated id (unique for each schedule in the db)
    @Id
    @Column(name = "ASSIGNEDCONTACT_ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

}
