package de.agdb.backend.data_model.schedule_wrapper_objects;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "schedule")
public class ScheduleWrapper {



    // An autogenerated id (unique for each schedule in the db)
    @Id
    @Column(name = "SCHEDULE_ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, targetEntity = DateWrapper.class)
    @JoinTable(name = "SCHEDULE_DAY", joinColumns = { @JoinColumn(name = "SCHEDULE_ID") }, inverseJoinColumns = { @JoinColumn(name = "DAY_ID") })
    private List<DateWrapper> days;
    private String title;
    private String description;
    private ZonedDateTime finalDate;
    private boolean recurrentEvent = false;
    private String recurrentMode;

    public String getRecurrentMode() {
        return recurrentMode;
    }

    public void setRecurrentMode(String recurrentMode) {
        this.recurrentMode = recurrentMode;
    }


    public void setRecurrentEvent(boolean bool ) {
        recurrentEvent = bool;
    }
    public boolean isRecurrentEvent() {
        return recurrentEvent;
    }

    public ZonedDateTime getFinalDate() {
        return finalDate;
    }

    public void setFinalDate(ZonedDateTime finalDate) {
        this.finalDate = finalDate;
    }

    public void setDays(List<DateWrapper> days) {
        this.days = days;
    }

    public List<DateWrapper> getDays() {
        return this.days;
    }


    public void setTitle(String title) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }


    public ScheduleWrapper() {
            days = new ArrayList<>();
    }

    public void addDay(DateWrapper e) {
        days.add(e);
        System.out.println("Day added" +  e.getDay());
    }

    public void removeAlldays() {
        days.clear();
    }

    public void removeDay(ZonedDateTime day) {
        for (int i=0; i<days.size();i++) {
            if ((days.get(i).getDay().compareTo(day)) == 0) {
                        days.remove(i);
                System.out.println("Day removed" + day);

                break;
            }
        }
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void clear() {

    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
