package de.agdb.entities;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Riva on 22.03.2017.
 */
@Entity
@Table(name = "categories")
public class Categories {


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    // An autogenerated id (unique for each category in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    @NotNull
    private String title;
    @NotNull
    private String description;
}
